// ============================================================================
// LocalizationService - 多語言管理服務（統一版本）
// ============================================================================
// 功能：管理所有模式的多語言字串
// - 語言狀態使用全域共用的 globalLanguageNotifier
// - 合併 Main 模式與 BodyDoor 模式的翻譯表
// - 衝突的 key 以 main_/bodydoor_ 前綴區分
// ============================================================================

import 'package:flutter/material.dart';
import 'package:flutter_firmware_tester_unified/shared/language_state.dart';

// 重新匯出 AppLanguage 讓現有 import 不需要改
export 'package:flutter_firmware_tester_unified/shared/language_state.dart';

/// 多語言管理服務（單例模式）
class LocalizationService {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  /// 當前語言通知器（指向全域共用狀態）
  ValueNotifier<AppLanguage> get currentLanguageNotifier => globalLanguageNotifier;

  /// 取得當前語言
  AppLanguage get currentLanguage => globalLanguageNotifier.value;

  /// 設定語言
  void setLanguage(AppLanguage language) {
    globalLanguageNotifier.value = language;
  }

  /// 取得翻譯字串
  String tr(String key) {
    final translations = _translations[currentLanguage];
    return translations?[key] ?? key;
  }

  /// 取得帶參數的翻譯字串
  /// 使用 {param} 格式的佔位符
  String trParams(String key, Map<String, dynamic> params) {
    String result = tr(key);
    params.forEach((paramKey, value) {
      result = result.replaceAll('{$paramKey}', value.toString());
    });
    return result;
  }

  /// 翻譯字串對照表（合併 Main 模式與 BodyDoor 模式）
  /// 衝突的 key 以 main_/bodydoor_ 前綴區分
  static final Map<AppLanguage, Map<String, String>> _translations = {
    // ==================== 繁體中文 ====================
    AppLanguage.zhTW: {
      // ================================================================
      // 共用翻譯
      // ================================================================

      // 應用程式標題
      'app_title': '命令控制',

      // 頁面標題（共用）
      'page_command_control': '命令控制',
      'page_data_storage': '資料儲存',
      'page_settings': '設定',

      // 頁面標題（衝突 — 以前綴區分）
      'main_page_auto_detection': '自動檢測流程-雙串口',
      'bodydoor_page_auto_detection': '自動檢測流程',
      'page_firmware_upload': '韌體燒錄',
      'page_operation': '操作畫面',

      // 側邊抽屜
      'drawer_title': '自動檢測流程系統',
      'drawer_subtitle': 'Arduino & STM32',
      'connection_status': '連接狀態',

      // 連接相關
      'connected': '已連接',
      'disconnected': '未連接',
      'not_connected': '未連接',
      'connect': '連接',
      'disconnect': '斷開',
      'select_com_port': '選擇 COM 埠',
      'connecting': '連接中',
      'verifying_device': '驗證裝置...',

      // Arduino 相關
      'arduino_control': 'Arduino 控制',
      'arduino_connected': 'Arduino 已連接',
      'arduino_disconnected': 'Arduino 已斷開',
      'arduino_connect_failed': 'Arduino 連接失敗，請稍後再試',
      'arduino_port_in_use': '此串口已被 STM32 使用',
      'select_arduino_port': '請先選擇 Arduino 串口',
      'connect_arduino_first': '請先連接 Arduino',
      'arduino_usb_removed': 'Arduino USB 已拔除，連接已自動關閉',
      'arduino_connection_error': 'Arduino 連接可能已斷開\n或連接錯誤',

      // STM32 相關（僅 Main 使用）
      'stm32_control': 'STM32 控制',
      'stm32_connected': 'STM32 已連接',
      'stm32_disconnected': 'STM32 已斷開',
      'stm32_connect_failed': 'STM32 連接失敗，請稍後再試',
      'stm32_port_in_use': '此串口已被 Arduino 使用',
      'select_stm32_port': '請先選擇 STM32 串口',
      'connect_stm32_first': '請先連接 STM32',
      'stm32_usb_removed': 'STM32 USB 已拔除，連接已自動關閉',
      'stm32_wrong_port': '連接的 COM 埠不是 STM32\n請選擇正確的 COM 埠',
      'stm32_connection_error': 'STM32 連接可能已斷開\n或連接錯誤',
      'firmware_version': '韌體版本',

      // COM 埠相關
      'no_com_port': '未偵測到任何 COM 埠，請檢查 USB 連接',
      'com_port_detected': '偵測到 {count} 個 COM 埠',
      'new_com_port_detected': '偵測到新 COM 埠: {ports}',

      // 硬體狀態
      'hardware_idle': '硬體無動作 (Idle)',
      'hardware_running': '硬體動作中 (Running)',
      'sensor_detection': '感應偵測',
      'show_adjacent_details': '顯示相鄰短路詳情',

      // 資料儲存頁面
      'arduino_data': 'Arduino 數據',
      'stm32_data': 'STM32 數據',
      'hardware_data': '硬體數據',
      'sensor_data': '感測器數據',
      'batch_read': '一鍵讀取',
      'stop': '停止',
      'stm32_output_control': 'STM32 輸出控制',
      'open_all_outputs': '開啟全部的輸出',
      'close_all_outputs': '關閉全部的輸出',

      // 表格欄位
      'column_name': '名稱',
      'column_arduino': 'Arduino',
      'column_stm32': 'STM32',
      'column_diff': '差值',
      'column_status': '狀態',

      // 設定頁面
      'settings': '設定',
      'detection_rules_title': '檢測規則說明',
      'detection_rules_desc': '查看所有自動檢測的規則、閾值設定和判斷條件',
      'reset_single': '恢復原廠',
      'reset_all': '全部恢復原廠',
      'reset_confirm_title': '確認恢復',
      'reset_confirm_msg': '確定要恢復此項目為原廠設定嗎？',
      'reset_all_confirm_msg': '確定要全部恢復為原廠設定嗎？',
      'reset_factory_done': '已恢復原廠設定',
      'value_saved': '已儲存',
      'min_label': '最小',
      'max_label': '最大',
      'value_label': '數值',
      'current_value': '當前值',
      'default_value': '預設值',
      'language': '語言',
      'language_setting': '語言設定',
      'select_language': '選擇語言',

      // 通用
      'send': '發送',
      'refresh': '刷新',
      'cancel': '取消',
      'confirm': '確認',
      'error': '錯誤',
      'warning': '警告',
      'success': '成功',
      'loading': '載入中...',
      'clear': '清除',

      // Arduino 面板（共用）
      'command_buttons': '指令按鈕:',
      'receive_log': '接收日誌:',
      'continuous_connection': '持續連接中',
      'connection_lost': '連線中斷',

      // Arduino 面板 — Main 模式指令
      'cmd_motor': '馬達 (ID 0-9)',
      'cmd_water_pump': '水泵 (ID 10)',
      'cmd_ozone': '臭氧 (ID 17)',
      'cmd_flow': '流量 (ID 18)',
      'cmd_relay': '繼電器 (ID 14-16)',
      'cmd_temperature': '溫度 (ID 21)',

      // Arduino 面板 — 衝突 key（以前綴區分）
      'main_cmd_uvc': '紫外燈 (ID 11-13)',
      'main_cmd_pressure': '壓力 (ID 19-20)',
      'bodydoor_cmd_uvc': 'UVC (ID 12-13)',
      'bodydoor_cmd_pressure': '壓力 (ID 10-11)',

      // Arduino 面板 — BodyDoor 模式指令
      'cmd_sensor': '感測器 (ID 0-5)',
      'cmd_sensor_ext': '感測器續 (ID 6-9)',
      'cmd_flowmeter2': '流量計2 (ID 14)',
      'cmd_bodypower': 'BodyPower (ID 15-18)',
      'cmd_tool': '工具',

      // STM32 面板（僅 Main 使用）
      'command_mode': '命令模式:',
      'mode_start': '啟動 (0x01)',
      'mode_stop': '停止 (0x02)',
      'mode_read': '讀取 (0x03)',
      'id_select_single': 'ID 選擇 (單選):',
      'id_select_multi': 'ID 選擇 (可多選):',
      'select_all': '全選',
      'select_id_to_preview': '請選擇 ID 以預覽命令',
      'command_preview': '命令預覽 (含 Header + CS):',
      'send_start_cmd': '發送啟動命令',
      'send_stop_cmd': '發送停止命令',
      'send_read_cmd': '發送讀取命令',
      'clear_flow': '清Flow',
      'custom_payload': '自訂 Payload',
      'hex_example': '16進制，例: 01 00 04 00 00',

      // 連接過程訊息
      'stm32_firmware_version': 'STM32 韌體版本: {version}',
      'arduino_connecting': 'Arduino 連接中... ({current}/{max})',
      'arduino_verifying': 'Arduino 連接中，驗證裝置...',
      'stm32_connecting': 'STM32 連接中... ({current}/{max})',
      'stm32_verifying': 'STM32 連接中，驗證裝置...',
      'sent_arduino_command': '已發送 Arduino 指令: {command}',
      'sent_stm32_read_command': '已發送 STM32 讀取指令: ID {id}',
      'all_outputs_toggled': '已{action}全部輸出',
      'output_opened': '開啟',
      'output_closed': '關閉',

      // 錯誤訊息
      'enter_payload': '請輸入 payload (不含 header 和 CS)',
      'hex_length_error': '16進制字串長度必須為偶數',
      'parse_error': '解析錯誤: {error}',

      // 自動檢測流程（共用）
      'auto_detection_start': '自動檢測開始',
      'auto_detection_running': '自動檢測進行中...',
      'auto_detection_step_connect': '步驟 1/6: 連接設備',
      'auto_detection_step_idle': '步驟 2/6: 讀取無動作狀態',
      'auto_detection_step_result': '步驟 6/6: 結果判定',
      'test_result_pass': '通過',
      'test_result_fail': '異常',
      'test_all_passed': '所有項目檢測通過',
      'test_failed_items': '以下項目異常:',
      'no_test_result': '尚無檢測結果',
      'slow_debug_mode_on': '慢速調試模式已開啟',
      'slow_debug_mode_off': '慢速調試模式已關閉',
      'debug_mode': '調試模式',
      'debug_pause': '暫停',
      'debug_resume': '繼續',
      'prev_record': '上一筆',
      'next_record': '下一筆',
      'usb_not_connected': '請將 USB 接上電腦',
      'retry_step': '重試中 ({current}/{max})...',
      'auto_detection_cancelled': '自動檢測已取消',
      'connecting_arduino': '正在連接 Arduino...',
      'reading_hardware_data': '讀取硬體數據...',

      // 自動檢測 — 僅 Main 使用
      'auto_detection_step_adjacent': '步驟 3/6: 相鄰腳位短路測試',
      'auto_detection_step_close': '步驟 4/6: 關閉輸出',
      'auto_detection_step_sensor': '步驟 5/6: 感測器測試',
      'connecting_stm32': '正在連接 STM32...',
      'starting_flow_test': '啟動流量計測試...',
      'stopping_flow_test': '停止流量計測試...',
      'vdd_short_detected': 'Vdd 短路 (電源短路)',
      'vss_short_detected': 'Vss 短路 (接地短路)',
      'adjacent_short_detected': '相鄰腳位短路',
      'd12v_short_detected': 'D極與12V短路',
      'sensor': '感測器',

      // 自動檢測 — 僅 BodyDoor 使用
      'power_33v_anomaly': '3.3V 電源異常（ID 6,8,9,10,11 數值全部過低）',
      'power_body12v_anomaly': 'Body 12V 電源異常（ID 0,1,2,3,4,5,7 數值全部過低，且 3.3V 異常）',
      'power_door24v_anomaly': 'Door 24V 升壓電路異常（BP_24V 數值過低）',
      'power_door12v_anomaly': 'Door 12V 電源異常（ID 12,13,14,16,17,18 數值全部過低）',

      // 短路測試設定（僅 Main 使用）
      'short_circuit_test_settings': '短路測試設定',
      'short_circuit_test_desc': '設定���否顯示 VDD/VSS 短路測試結果',
      'show_vdd_short_test': '顯示 VDD 短路測試',
      'show_vdd_short_test_desc': '電源短路測試（Idle 數值落入 Running 範��）',
      'show_vss_short_test': '顯示 VSS 短路測試',
      'show_vss_short_test_desc': '接地短路測試（Running 數值落入 Idle 範圍）',
      'adjacent_short_test_optimization': '相鄰短路測試優化',
      'adjacent_short_test_optimization_desc': '開啟時跳過已測試的配對，關閉時測試所有相鄰配對',
      'adjacent_short_display_mode': '相鄰短路顯示模式',
      'adjacent_short_display_mode_desc': '切換相鄰腳位測試數值的顯示位置',
      'adjacent_display_in_idle': '顯示在 Idle 區域（傳統模式）',
      'adjacent_display_in_running': '顯示在 Running 區域（新模式）',
      'adjacent_info': '相鄰短路',
      'adjacent_idle_1': '相鄰1',
      'adjacent_idle_2': '相鄰2',

      // 診斷偵測設定（僅 Main 使用）
      'diagnostic_detection_settings': '診斷偵測設定',
      'diagnostic_detection_desc': '設定自動檢測時顯示的診斷資訊',
      'show_load_detection': '負載偵測',
      'show_load_detection_desc': '偵測負載是否連接（Running < 100 且 Idle < 50）',
      'show_mosfet_detection': 'MOSFET 異常偵測',
      'show_mosfet_detection_desc': '偵測 MOSFET 腳位短路或接地異常（G-D、D-S、G-S 短路、D/G 極接地）',
      'show_gpio_status_detection': 'GPIO 狀態偵測',
      'show_gpio_status_detection_desc': '偵測 GPIO 是否卡在 ON 或 OFF 狀態',
      'show_wire_error_detection': '線材錯誤偵測',
      'show_wire_error_detection_desc': '偵測 Arduino 端線材是否接錯或斷開',

      // 診斷結果訊息（僅 Main 使用）
      'diag_load_disconnected': '負載未連接',
      'diag_gs_short': 'MOSFET 診斷',
      'diag_gpio_stuck_on': 'GPIO 卡在 ON',
      'diag_gpio_stuck_off': 'GPIO 卡在 OFF',
      'diag_wire_error': '線材錯誤',
      'diag_normal': '正常',
      'diag_detail_title': '診斷詳情',
      'diag_stm32_idle': 'STM32 Idle: {value}',
      'diag_stm32_running': 'STM32 Running: {value}',

      // Debug mode messages（僅 Main 使用）
      'debug_running_title': '【Running】{pinName} (ID{id})',
      'debug_adjacent_ids': '【相鄰 ID】{ids}',
      'debug_test_adjacent': '【{index}】檢測相鄰: {pinName} (ID{id})',
      'debug_pair': '配對: {smallName} ↔ {largeName}',
      'debug_stm32_result': 'STM32: 基準{base} → 新值{newVal} 差:{diff} {status}',
      'debug_arduino_result': 'Arduino: 基準{base} → 新值{newVal} 差:{diff} {status}',
      'debug_threshold': '閾值: {value}',
      'debug_status_short': '❌短路',
      'debug_status_normal': '✓正常',
      'debug_na': 'N/A',

      // 檢測規則頁面（共用）
      'rules_threshold_section': '閾值檢測規則',
      'rules_arduino_idle_title': 'Arduino Idle 閾值',
      'rules_arduino_idle_desc': 'Arduino 在無動作狀態下的 ADC 數值範圍',
      'rules_polling_section': '輪詢機制',
      'rules_polling_retry_title': '資料讀取重試',
      'rules_polling_retry_desc': '當某個 ID 沒有收到回應時的重試機制',
      'rules_polling_max_retry_label': '最大重試次數',
      'rules_polling_hw_wait_label': '硬體等待 (ms)',

      // 檢測規則 — 僅 Main 使用
      'rules_arduino_running_title': 'Arduino Running 閾值',
      'rules_arduino_running_desc': 'Arduino 在動作中狀態下的 ADC 數值範圍',
      'rules_stm32_idle_title': 'STM32 Idle 閾值',
      'rules_stm32_idle_desc': 'STM32 在無動作狀態下的 ADC 數值範圍',
      'rules_stm32_running_title': 'STM32 Running 閾值',
      'rules_stm32_running_desc': 'STM32 在動作中狀態下的 ADC 數值範圍',
      'rules_range_770_830': '正常範圍：770 ~ 830',
      'rules_range_25_60': '正常範圍：25 ~ 60',
      'rules_range_0_55': '正常範圍：0 ~ 55',
      'rules_range_300_380': '正常範圍：300 ~ 380',
      'rules_out_of_range_error': '超出範圍則判定為異常',
      'rules_short_circuit_section': '短路測試規則',
      'rules_vdd_short_title': 'Vdd 短路（電源短路）',
      'rules_vdd_short_desc': 'Idle 狀態下數值異常偏高，落入 Running 範圍',
      'rules_vdd_short_cond1': '判定條件：Idle 值落入 Running 閾值範圍',
      'rules_vdd_short_cond2': '且 Idle 值不在 Idle 閾值範圍內',
      'rules_vdd_short_reason': '原因：Vdd 短路導致電流持續流通',
      'rules_d12v_short_title': 'D極與12V短路',
      'rules_d12v_short_desc': 'MOSFET D極與電路板 12V 電源短路',
      'rules_d12v_short_cond1': '判定條件：Arduino Idle > 1000',
      'rules_d12v_short_cond2': '且 Arduino Running > 1000',
      'rules_d12v_short_feature': '特徵：Arduino ADC 接近飽和值（10-bit ADC 最大 1023）',
      'rules_d12v_short_reason': '原因：D極被 12V 強制拉高',
      'rules_adjacent_short_title': '相鄰腳位短路',
      'rules_adjacent_short_desc': '相鄰的 GPIO 腳位之間發生短路',
      'rules_adjacent_short_cond': '判定條件：相鄰腳位的 Idle 基準值變化超過閾值',
      'rules_adjacent_short_threshold': '預設閾值：15',
      'rules_adjacent_short_method': '測試方式：啟動測試腳位，讀取相鄰腳位的數值變化',
      'rules_adjacent_short_label': '短路閾值',
      'rules_diagnostic_section': '診斷偵測規則',
      'rules_condition_header': '判定條件：',
      'rules_load_disconnected_title': '負載未連接',
      'rules_load_disconnected_desc': 'GPIO 腳位的負載（如 LED、繼電器）未正確連接',
      'rules_load_disconnected_cond_header': '判定條件（需同時滿足）：',
      'rules_load_disconnected_cond1': '1. Arduino Idle 與 Running 差異 < 180',
      'rules_load_disconnected_cond2': '2. STM32 Running 在 40 ~ 70（異常低）',
      'rules_load_disconnected_cond3': '3. STM32 Idle 在正常範圍內',
      'rules_load_disconnected_feature': '特徵：沒有偵測到電流變化',
      'rules_gd_short_title': 'G-D 短路（Gate-Drain 短路）',
      'rules_gd_short_desc': 'MOSFET Gate 極與 Drain 極短路',
      'rules_gd_short_cond1': '1. Arduino Idle < 10（接近 0）',
      'rules_gd_short_cond2': '2. Arduino Running 在 350 ~ 480',
      'rules_gd_short_cond3': '3. STM32 Running 在 420 ~ 570',
      'rules_ds_short_title': 'D-S 短路（Drain-Source 短路）',
      'rules_ds_short_desc': 'MOSFET Drain 極與 Source 極短路',
      'rules_ds_short_cond1': '1. Arduino Idle 在 25 ~ 60（落入 Running 範圍）',
      'rules_ds_short_cond2': '2. STM32 Idle 在 330 ~ 375（落入 Running 範圍）',
      'rules_d_grounded_title': 'D 極接地',
      'rules_d_grounded_desc': 'MOSFET Drain 極接地',
      'rules_d_grounded_cond': '判定條件：Arduino Idle < 10（接近 0）',
      'rules_d_grounded_feature': '特徵：D極被拉到接地電位',
      'rules_d_grounded_label': 'Arduino ADC <',
      'rules_g_grounded_title': 'G 極接地',
      'rules_g_grounded_desc': 'MOSFET Gate 極接地',
      'rules_g_grounded_cond1': '1. Arduino Idle ≥ 700（正常）',
      'rules_g_grounded_cond2': '2. Arduino Running ≥ 700（維持 Idle 值）',
      'rules_g_grounded_cond3': '3. STM32 Idle < 50（很低）',
      'rules_g_grounded_cond4': '4. STM32 Running < 100（很低）',
      'rules_g_grounded_feature': '特徵：Gate 無法控制，MOSFET 不導通',
      'rules_gs_short_title': 'G-S 短路（Gate-Source 短路）',
      'rules_gs_short_desc': 'MOSFET Gate 極與 Source 極短路',
      'rules_gs_short_cond1': '1. STM32 Running > 400',
      'rules_gs_short_cond2': '2. STM32 Idle < 50',
      'rules_wire_error_title': '線材錯誤偵測',
      'rules_wire_error_desc': 'Arduino 端線材接錯或斷開，導致 Idle/Running 差異過小',
      'rules_sensor_section': '感測器檢測規則',
      'rules_sensor_flow_title': 'Flow（流量計）',
      'rules_sensor_flow_desc': 'ID18 - 流量感測器',
      'rules_sensor_flow_arduino': 'Arduino 正常範圍：0 ~ 10000',
      'rules_sensor_flow_stm32': 'STM32 正常範圍：0 ~ 10000',
      'rules_sensor_pressure_co2_title': 'PressureCO2（CO2壓力）',
      'rules_sensor_pressure_co2_desc': 'ID19 - CO2 壓力感測器',
      'rules_sensor_pressure_co2_arduino': 'Arduino 正常範圍：190 ~ 260',
      'rules_sensor_pressure_co2_stm32': 'STM32 正常範圍：930 ~ 980',
      'rules_sensor_pressure_water_title': 'PressureWater（水壓）',
      'rules_sensor_pressure_water_desc': 'ID20 - 水壓感測器',
      'rules_sensor_pressure_water_arduino': 'Arduino 正常範圍：190 ~ 260',
      'rules_sensor_pressure_water_stm32': 'STM32 正常範圍：930 ~ 980',
      'rules_sensor_mcu_temp_title': 'MCUtemp（MCU溫度）',
      'rules_sensor_mcu_temp_desc': 'ID21 - MCU 內部溫度感測器',
      'rules_sensor_mcu_temp_arduino': 'Arduino 正常範圍：-20°C ~ 100°C（原始值除以10）',
      'rules_sensor_mcu_temp_stm32': 'STM32 正常範圍：-20°C ~ 100°C',
      'rules_sensor_water_temp_title': 'WATERtemp（水溫）',
      'rules_sensor_water_temp_desc': 'ID22 - 水溫感測器（DS18B20）',
      'rules_sensor_water_temp_stm32': 'STM32 正常範圍：-20°C ~ 100°C',
      'rules_sensor_temp_error_title': '溫度感測器異常值',
      'rules_sensor_temp_error_desc': '溫度感測器回報 85°C 表示未連接或損壞',
      'rules_sensor_temp_error_label': '異常溫度值 (°C)',
      'rules_sensor_temp_error_85': '異常值：85°C 表示感測器未連接或損壞',
      'rules_sensor_bib_temp_title': 'BIBtemp（BIB溫度）',
      'rules_sensor_bib_temp_desc': 'ID23 - BIB 溫度感測器（DS18B20）',
      'rules_sensor_bib_temp_stm32': 'STM32 正常範圍：-20°C ~ 100°C',
      'rules_polling_retry_step1': '第一輪：依序讀取所有 ID',
      'rules_polling_retry_step2': '第二輪：只對沒有資料的 ID 單獨重試',
      'rules_polling_retry_max': '每個 ID 最多重試 5 次',
      'rules_polling_retry_wait': '等待時間：硬體 300ms，感測器 400ms',
      'rules_polling_sensor_wait_label': '感測器等待 (ms)',

      // 檢測規則 — 僅 BodyDoor 使用
      'rules_33v_section': '3.3V 電源異常偵測',
      'rules_33v_title': '3.3V 電源異常判定',
      'rules_33v_desc': '當以下 5 個 3.3V 感測器的 ADC 數值同時低於閾值時，判定為 3.3V 電源異常',
      'rules_33v_ids': '檢測 ID：BibTemp、WaterTemp、Leak、WaterPressure、CO2Pressure',
      'rules_33v_threshold_label': '異常閾值（低於此值）',
      'rules_33v_condition': '觸發條件：以上 5 個 ID 的數值「全部」低於閾值',
      'rules_33v_action_realtime': '即時警告：DataStorage 頁面和 AutoDetection 頁面顯示紅色警告橫幅',
      'rules_33v_action_result': '檢測結果：自動偵測結果中標記「3.3V 電源異常」',
      'rules_body12v_section': 'Body 12V 電源異常偵測',
      'rules_body12v_title': 'Body 12V 電源異常判定',
      'rules_body12v_desc': '當以下 7 個 Body 12V 通道的 ADC 數值同時低於閾值，且 3.3V 電源異常也被觸發時，判定為 Body 12V 電源異常',
      'rules_body12v_ids': '檢測 ID：AmbientRL、CoolRL、SparklingRL、WaterPump、O3、MainUVC、FlowMeter',
      'rules_body12v_threshold_label': '異常閾值（低於此值）',
      'rules_body12v_condition': '觸發條件：以上 7 個 ID 的數值「全部」低於閾值',
      'rules_body12v_prerequisite': '前置條件：3.3V 電源異常必須同時被觸發（階層式檢測）',
      'rules_body12v_action_realtime': '即時警告：DataStorage 頁面和 AutoDetection 頁面顯示深橘色警告橫幅',
      'rules_body12v_action_result': '檢測結果：自動偵測結果中標記「Body 12V 電源異常」',
      'rules_door24v_section': 'Door 24V 升壓電路異常偵測',
      'rules_door24v_title': 'Door 24V 升壓電路異常判定',
      'rules_door24v_desc': '當 BP_24V 的 ADC 數值低於閾值時，判定為升壓電路異常',
      'rules_door24v_ids': '檢測 ID：BP_24V',
      'rules_door24v_threshold_label': '異常閾值（低於此值）',
      'rules_door24v_condition': '觸發條件：BP_24V 數值低於閾值',
      'rules_door24v_action_realtime': '即時警告：DataStorage 頁面和 AutoDetection 頁面顯示紫色警告橫幅',
      'rules_door24v_action_result': '檢測結果：自動偵測結果中標記「Door 24V 升壓電路異常」',
      'rules_door12v_section': 'Door 12V 電源異常偵測',
      'rules_door12v_title': 'Door 12V 電源異常判定',
      'rules_door12v_desc': '當以下 6 個 Door 12V 通道的 ADC 數值同時低於閾值時，判定為 Door 12V 電源異常',
      'rules_door12v_ids': '檢測 ID：SpoutUVC、MixUVC、FlowMeter2、BP_12V、BP_UpScreen、BP_LowScreen',
      'rules_door12v_threshold_label': '異常閾值（低於此值）',
      'rules_door12v_condition': '觸發條件：以上 6 個 ID 的數值「全部」低於閾值',
      'rules_door12v_action_realtime': '即時警告：DataStorage 頁面和 AutoDetection 頁面顯示靛藍色警告橫幅',
      'rules_door12v_action_result': '檢測結果：自動偵測結果中標記「Door 12V 電源異常」',

      // 操作畫面（僅 Main 使用）
      'operation_auto_connect': '自動連線 STM32',
      'operation_connecting': '正在連線...',
      'operation_connected': 'STM32 已連線',
      'operation_connect_failed': 'STM32 連線失敗',
      'operation_warm_water': '常溫水',
      'operation_stop': '停',
      'operation_warm_water_desc': '開啟 ID10~ID14',
      'operation_stop_desc': '關閉 ID0~ID17',
      'operation_stm32_not_connected': '請先連線 STM32',
      'operation_warm_water_sent': '已送出常溫水指令 (ID10~ID14 開啟)',
      'operation_stop_sent': '已送出停止指令 (ID0~ID17 關閉)',

      // 閾值設定（共用）
      'threshold_settings': '閾值設定',
      'threshold_settings_desc': '設定自動檢測的數值範圍',
      'arduino_idle_threshold': 'Arduino 無動作閾值',
      'idle_threshold': '無動作閾值',
      'min_value': '最小值',
      'max_value': '最大值',
      'threshold_range': '範圍',
      'reset_to_defaults': '恢復初始設定',
      'reset_all_confirm': '確定要恢復所有閾值為初始設定嗎？',
      'reset_success': '已恢復初始設定',
      'save_success': '設定已儲存',
      'apply_to_all': '套用到所有 ID',
      'edit_threshold': '編輯閾值',
      'id_label': 'ID {id}',
      'value_out_of_range': '數值超出範圍',

      // 閾值設定 — 僅 Main 使用
      'arduino_running_threshold': 'Arduino 動作中閾值',
      'stm32_idle_threshold': 'STM32 無動作閾值',
      'stm32_running_threshold': 'STM32 動作中閾值',
      'running_threshold': '動作中閾值',
      'sensor_threshold': '感測器閾值',
      'diff_threshold': '差值閾值',

      // 閾值設定 — 衝突 key（以前綴區分）
      'main_hardware_threshold': '硬體閾值 (ID 0-17)',
      'bodydoor_hardware_threshold': '硬體閾值 (ID 0-18)',

      // 韌體燒錄頁面（僅 Main 使用）
      'firmware_upload': '韌體燒錄',
      'checking_stlink': '檢查 ST-Link 連接...',
      'stlink_connected': 'ST-Link 已連接',
      'stlink_not_connected': 'ST-Link 未連接',
      'refresh_stlink': '刷新 ST-Link 狀態',
      'cli_not_found': '找不到 STM32CubeProgrammer CLI',
      'cli_not_found_hint': '請確認已安裝 STM32CubeProgrammer，CLI 工具應位於以下路徑：',
      'status': '狀態',
      'version': '版本',
      'serial_number': '序號',
      'firmware_file': '韌體檔案',
      'click_to_select': '點擊選擇韌體檔案',
      'select_firmware_file': '選擇韌體檔案',
      'supported_formats': '支援格式: .elf, .bin, .hex',
      'program_options': '燒錄選項',
      'verify_after_program': '燒錄後驗證',
      'verify_hint': '驗證寫入的資料是否正確',
      'reset_after_program': '燒錄後重置',
      'reset_hint': '燒錄完成後自動重置 MCU',
      'program_firmware': '燒錄韌體',
      'programming': '燒錄中...',
      'please_select_firmware': '請先選擇韌體檔案',
      'starting_program': '開始燒錄...',
      'waiting_stm32_startup': '等待 STM32 啟動中...',
      'program_success': '韌體燒錄成功',
      'erase': '擦除',
      'reset': '重置',
      'confirm_erase': '確認擦除',
      'erase_warning': '這將擦除 STM32 上的所有韌體，確定要繼續嗎？',
      'erasing_flash': '擦除 Flash...',
      'resetting_mcu': '重置 MCU...',
      'progress': '進度',
      'stlink_frequency': 'ST-Link 頻率',
      'stlink_frequency_hint': 'SWD 通訊頻率 (kHz)',
      'cli_output': 'CLI 輸出訊息',
      'select_other_file': '選擇其他檔案...',
      'firmware_folder_hint': '韌體檔案請放置於 firmware 資料夾',
      'connect_mode': '連接模式',
      'connect_mode_hint': 'ST-Link 連接模式設定',
      'reset_mode': '重置模式',
      'reset_mode_hint': 'MCU 重置方式',
      'program_timeout': '燒錄超時',
      'erase_timeout': '擦除超時',
      'reset_timeout': '重置超時',
      'check_timeout': '連接檢查超時',
      'disconnecting_stm32_for_program': '燒錄前斷開 STM32 連線...',
      'program_success_retry': '韌體燒錄成功（第 {attempt} 次嘗試，頻率 {frequency} kHz）',
      'program_timeout_error': '燒錄超時 (120秒)',
      'firmware_file_not_found': '韌體檔案不存在',
      'unsupported_file_format': '不支援的檔案格式: .{extension}',
      'stlink_not_detected': 'ST-Link 未連接',
      'target_not_connected': '目標 MCU 未連接',
      'flash_erase_failed': 'Flash 擦除失敗',
      'program_failed': '燒錄失敗',
      'execution_error': '執行錯誤',
      'erase_timeout_error': '擦除超時 (60秒)',
      'erase_completed': '擦除完成',
      'erase_failed': '擦除失敗',
      'erase_error': '擦除錯誤',
      'mcu_reset_timeout_error': '重置超時 (30秒)',
      'mcu_reset_completed': 'MCU 重置完成',
      'mcu_reset_failed': 'MCU 重置失敗',
      'mcu_reset_error': 'MCU 重置錯誤',
      'no_firmware_files': '無韌體檔案',
      'select_firmware': '選擇韌體',
      'program_and_detect': '燒入並檢測',

      // CLI 工具檢查對話框（僅 Main 使用）
      'cli_check_title': '缺少必要工具',
      'cli_check_description': '程式需要以下外部工具才能使用燒錄功能，請先安裝：',
      'cli_status_installed': '已安裝',
      'cli_status_not_found': '未偵測到',
      'cli_install_instruction': '安裝說明：',
      'cli_installer_found': '已找到安裝程式',
      'cli_run_installer': '執行安裝',
      'cli_download_instruction': '請從 ST 官網下載：',
      'cli_installer_tip': '提示：可將安裝程式放到 tools 資料夾以便日後使用',
      'cli_open_tools_folder': '開啟 tools 資料夾',
      'cli_skip_continue': '略過，繼續使用',
      'cli_recheck': '重新檢查',

      // 跨模式偵測（衝突 — 以前綴區分）
      'wrong_mode_detected': '偵測到不同模式的裝置',
      'wrong_mode_detected_title': '偵測到不同模式的裝置',
      'main_wrong_mode_detected_message': '偵測到 Body&Door Board 的 Arduino，是否切換到正確模式？',
      'bodydoor_wrong_mode_detected_message': '偵測到 Main Board 的 Arduino，是否切換到正確模式？',
      'switch_to_bodydoor_mode': '切換到 Body&Door 模式',
      'switch_to_main_mode': '切換到 Main 模式',
      'switch_mode': '切換模式',
    },

    // ==================== English ====================
    AppLanguage.en: {
      // ================================================================
      // 共用翻譯
      // ================================================================

      // App title
      'app_title': 'Command Control',

      // Page titles（共用）
      'page_command_control': 'Command Control',
      'page_data_storage': 'Data Storage',
      'page_settings': 'Settings',

      // Page titles（衝突 — 以前綴區分）
      'main_page_auto_detection': 'Auto Detection - Dual Serial',
      'bodydoor_page_auto_detection': 'Auto Detection',
      'page_firmware_upload': 'Firmware Upload',
      'page_operation': 'Operation',

      // Drawer
      'drawer_title': 'Auto Detection System',
      'drawer_subtitle': 'Arduino & STM32',
      'connection_status': 'Connection Status',

      // Connection related
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'not_connected': 'Not Connected',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'select_com_port': 'Select COM Port',
      'connecting': 'Connecting',
      'verifying_device': 'Verifying device...',

      // Arduino related
      'arduino_control': 'Arduino Control',
      'arduino_connected': 'Arduino Connected',
      'arduino_disconnected': 'Arduino Disconnected',
      'arduino_connect_failed': 'Arduino connection failed, please try again',
      'arduino_port_in_use': 'This port is already used by STM32',
      'select_arduino_port': 'Please select Arduino port first',
      'connect_arduino_first': 'Please connect Arduino first',
      'arduino_usb_removed': 'Arduino USB removed, connection closed',
      'arduino_connection_error': 'Arduino connection may be lost\nor connection error',

      // STM32 related（僅 Main）
      'stm32_control': 'STM32 Control',
      'stm32_connected': 'STM32 Connected',
      'stm32_disconnected': 'STM32 Disconnected',
      'stm32_connect_failed': 'STM32 connection failed, please try again',
      'stm32_port_in_use': 'This port is already used by Arduino',
      'select_stm32_port': 'Please select STM32 port first',
      'connect_stm32_first': 'Please connect STM32 first',
      'stm32_usb_removed': 'STM32 USB removed, connection closed',
      'stm32_wrong_port': 'Connected COM port is not STM32\nPlease select correct COM port',
      'stm32_connection_error': 'STM32 connection may be lost\nor connection error',
      'firmware_version': 'Firmware Version',

      // COM port related
      'no_com_port': 'No COM port detected, please check USB connection',
      'com_port_detected': 'Detected {count} COM port(s)',
      'new_com_port_detected': 'New COM port detected: {ports}',

      // Hardware status
      'hardware_idle': 'Hardware Idle',
      'hardware_running': 'Hardware Running',
      'sensor_detection': 'Sensor Detection',
      'show_adjacent_details': 'Show Adjacent Short Details',

      // Data storage page
      'arduino_data': 'Arduino Data',
      'stm32_data': 'STM32 Data',
      'hardware_data': 'Hardware Data',
      'sensor_data': 'Sensor Data',
      'batch_read': 'Batch Read',
      'stop': 'Stop',
      'stm32_output_control': 'STM32 Output Control',
      'open_all_outputs': 'Open All Outputs',
      'close_all_outputs': 'Close All Outputs',

      // Table columns
      'column_name': 'Name',
      'column_arduino': 'Arduino',
      'column_stm32': 'STM32',
      'column_diff': 'Diff',
      'column_status': 'Status',

      // Settings page
      'settings': 'Settings',
      'detection_rules_title': 'Detection Rules',
      'detection_rules_desc': 'View all auto-detection rules, thresholds and conditions',
      'reset_single': 'Reset',
      'reset_all': 'Reset All',
      'reset_confirm_title': 'Confirm Reset',
      'reset_confirm_msg': 'Reset this item to factory defaults?',
      'reset_all_confirm_msg': 'Reset all settings to factory defaults?',
      'reset_factory_done': 'Reset to factory defaults',
      'value_saved': 'Saved',
      'min_label': 'Min',
      'max_label': 'Max',
      'value_label': 'Value',
      'current_value': 'Current',
      'default_value': 'Default',
      'language': 'Language',
      'language_setting': 'Language Setting',
      'select_language': 'Select Language',

      // General
      'send': 'Send',
      'refresh': 'Refresh',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'error': 'Error',
      'warning': 'Warning',
      'success': 'Success',
      'loading': 'Loading...',
      'clear': 'Clear',

      // Arduino panel（共用）
      'command_buttons': 'Commands:',
      'receive_log': 'Receive Log:',
      'continuous_connection': 'Connected',
      'connection_lost': 'Connection Lost',

      // Arduino panel — Main 模式指令
      'cmd_motor': 'Motor (ID 0-9)',
      'cmd_water_pump': 'Water Pump (ID 10)',
      'cmd_ozone': 'Ozone (ID 17)',
      'cmd_flow': 'Flow (ID 18)',
      'cmd_relay': 'Relay (ID 14-16)',
      'cmd_temperature': 'Temp (ID 21)',

      // Arduino panel — 衝突 key（以前綴區分）
      'main_cmd_uvc': 'UVC (ID 11-13)',
      'main_cmd_pressure': 'Pressure (ID 19-20)',
      'bodydoor_cmd_uvc': 'UVC (ID 12-13)',
      'bodydoor_cmd_pressure': 'Pressure (ID 10-11)',

      // Arduino panel — BodyDoor 模式指令
      'cmd_sensor': 'Sensor (ID 0-5)',
      'cmd_sensor_ext': 'Sensor Ext (ID 6-9)',
      'cmd_flowmeter2': 'FlowMeter2 (ID 14)',
      'cmd_bodypower': 'BodyPower (ID 15-18)',
      'cmd_tool': 'Tool',

      // STM32 panel（僅 Main）
      'command_mode': 'Command Mode:',
      'mode_start': 'Start (0x01)',
      'mode_stop': 'Stop (0x02)',
      'mode_read': 'Read (0x03)',
      'id_select_single': 'ID Select (Single):',
      'id_select_multi': 'ID Select (Multi):',
      'select_all': 'All',
      'select_id_to_preview': 'Select ID to preview command',
      'command_preview': 'Command Preview (with Header + CS):',
      'send_start_cmd': 'Send Start Command',
      'send_stop_cmd': 'Send Stop Command',
      'send_read_cmd': 'Send Read Command',
      'clear_flow': 'ClearFlow',
      'custom_payload': 'Custom Payload',
      'hex_example': 'Hex, e.g.: 01 00 04 00 00',

      // Connection process messages
      'stm32_firmware_version': 'STM32 Firmware: {version}',
      'arduino_connecting': 'Arduino connecting... ({current}/{max})',
      'arduino_verifying': 'Arduino connecting, verifying device...',
      'stm32_connecting': 'STM32 connecting... ({current}/{max})',
      'stm32_verifying': 'STM32 connecting, verifying device...',
      'sent_arduino_command': 'Sent Arduino command: {command}',
      'sent_stm32_read_command': 'Sent STM32 read command: ID {id}',
      'all_outputs_toggled': 'All outputs {action}',
      'output_opened': 'opened',
      'output_closed': 'closed',

      // Error messages
      'enter_payload': 'Enter payload (without header and CS)',
      'hex_length_error': 'Hex string length must be even',
      'parse_error': 'Parse error: {error}',

      // Auto detection（共用）
      'auto_detection_start': 'Auto Detect',
      'auto_detection_running': 'Detecting...',
      'auto_detection_step_connect': 'Step 1/6: Connecting Devices',
      'auto_detection_step_idle': 'Step 2/6: Reading Idle State',
      'auto_detection_step_result': 'Step 6/6: Result Check',
      'test_result_pass': 'Pass',
      'test_result_fail': 'Error',
      'test_all_passed': 'All items passed',
      'test_failed_items': 'Failed items:',
      'no_test_result': 'No test result yet',
      'slow_debug_mode_on': 'Slow debug mode enabled',
      'slow_debug_mode_off': 'Slow debug mode disabled',
      'debug_mode': 'Debug Mode',
      'debug_pause': 'Pause',
      'debug_resume': 'Resume',
      'prev_record': 'Previous',
      'next_record': 'Next',
      'usb_not_connected': 'Please connect USB to computer',
      'retry_step': 'Retrying ({current}/{max})...',
      'auto_detection_cancelled': 'Auto detection cancelled',
      'connecting_arduino': 'Connecting Arduino...',
      'reading_hardware_data': 'Reading hardware data...',

      // Auto detection — 僅 Main
      'auto_detection_step_adjacent': 'Step 3/6: Adjacent Pin Short Test',
      'auto_detection_step_close': 'Step 4/6: Closing Outputs',
      'auto_detection_step_sensor': 'Step 5/6: Sensor Test',
      'connecting_stm32': 'Connecting STM32...',
      'starting_flow_test': 'Starting flow test...',
      'stopping_flow_test': 'Stopping flow test...',
      'vdd_short_detected': 'Vdd Short (Power Short)',
      'vss_short_detected': 'Vss Short (Ground Short)',
      'adjacent_short_detected': 'Adjacent Pin Short',
      'd12v_short_detected': 'Drain-12V Short',
      'sensor': 'Sensor',

      // Auto detection — 僅 BodyDoor
      'power_33v_anomaly': '3.3V power anomaly (ID 6,8,9,10,11 all below threshold)',
      'power_body12v_anomaly': 'Body 12V power anomaly (ID 0,1,2,3,4,5,7 all below threshold + 3.3V anomaly)',
      'power_door24v_anomaly': 'Door 24V boost circuit anomaly (BP_24V below threshold)',
      'power_door12v_anomaly': 'Door 12V power anomaly (ID 12,13,14,16,17,18 all below threshold)',

      // Short circuit test settings（僅 Main）
      'short_circuit_test_settings': 'Short Circuit Test',
      'short_circuit_test_desc': 'Configure VDD/VSS short circuit test display',
      'show_vdd_short_test': 'Show VDD Short Test',
      'show_vdd_short_test_desc': 'Power short test (Idle value in Running range)',
      'show_vss_short_test': 'Show VSS Short Test',
      'show_vss_short_test_desc': 'Ground short test (Running value in Idle range)',
      'adjacent_short_test_optimization': 'Adjacent Short Test Optimization',
      'adjacent_short_test_optimization_desc': 'When enabled, skip tested pairs; when disabled, test all adjacent pairs',
      'adjacent_short_display_mode': 'Adjacent Short Display Mode',
      'adjacent_short_display_mode_desc': 'Toggle display location for adjacent pin test values',
      'adjacent_display_in_idle': 'Display in Idle area (Traditional)',
      'adjacent_display_in_running': 'Display in Running area (New)',
      'adjacent_info': 'Adjacent',
      'adjacent_idle_1': 'Adj 1',
      'adjacent_idle_2': 'Adj 2',

      // Diagnostic detection settings（僅 Main）
      'diagnostic_detection_settings': 'Diagnostic Detection',
      'diagnostic_detection_desc': 'Configure diagnostic info display during auto detection',
      'show_load_detection': 'Load Detection',
      'show_load_detection_desc': 'Detect if load is connected (Running < 100 and Idle < 50)',
      'show_mosfet_detection': 'MOSFET Fault Detection',
      'show_mosfet_detection_desc': 'Detect MOSFET pin short or ground faults (G-D, D-S, G-S short, D/G grounded)',
      'show_gpio_status_detection': 'GPIO Status Detection',
      'show_gpio_status_detection_desc': 'Detect if GPIO is stuck ON or OFF',
      'show_wire_error_detection': 'Wire Error Detection',
      'show_wire_error_detection_desc': 'Detect if Arduino side wire is misconnected or broken',

      // Diagnostic result messages（僅 Main）
      'diag_load_disconnected': 'Load Disconnected',
      'diag_gs_short': 'MOSFET Diagnostic',
      'diag_gpio_stuck_on': 'GPIO Stuck ON',
      'diag_gpio_stuck_off': 'GPIO Stuck OFF',
      'diag_wire_error': 'Wire Error',
      'diag_normal': 'Normal',
      'diag_detail_title': 'Diagnostic Details',
      'diag_stm32_idle': 'STM32 Idle: {value}',
      'diag_stm32_running': 'STM32 Running: {value}',

      // Debug mode messages（僅 Main）
      'debug_running_title': '[Running] {pinName} (ID{id})',
      'debug_adjacent_ids': '[Adjacent IDs] {ids}',
      'debug_test_adjacent': '[{index}] Testing Adjacent: {pinName} (ID{id})',
      'debug_pair': 'Pair: {smallName} ↔ {largeName}',
      'debug_stm32_result': 'STM32: Base {base} → New {newVal} Diff:{diff} {status}',
      'debug_arduino_result': 'Arduino: Base {base} → New {newVal} Diff:{diff} {status}',
      'debug_threshold': 'Threshold: {value}',
      'debug_status_short': '❌Short',
      'debug_status_normal': '✓Normal',
      'debug_na': 'N/A',

      // Detection rules（共用）
      'rules_threshold_section': 'Threshold Detection Rules',
      'rules_arduino_idle_title': 'Arduino Idle Threshold',
      'rules_arduino_idle_desc': 'ADC value range when Arduino is idle',
      'rules_polling_section': 'Polling Mechanism',
      'rules_polling_retry_title': 'Data Read Retry',
      'rules_polling_retry_desc': 'Retry mechanism when an ID does not receive response',
      'rules_polling_max_retry_label': 'Max retries',
      'rules_polling_hw_wait_label': 'Hardware wait (ms)',

      // Detection rules — 僅 Main
      'rules_arduino_running_title': 'Arduino Running Threshold',
      'rules_arduino_running_desc': 'ADC value range when Arduino is running',
      'rules_stm32_idle_title': 'STM32 Idle Threshold',
      'rules_stm32_idle_desc': 'ADC value range when STM32 is idle',
      'rules_stm32_running_title': 'STM32 Running Threshold',
      'rules_stm32_running_desc': 'ADC value range when STM32 is running',
      'rules_range_770_830': 'Normal range: 770 ~ 830',
      'rules_range_25_60': 'Normal range: 25 ~ 60',
      'rules_range_0_55': 'Normal range: 0 ~ 55',
      'rules_range_300_380': 'Normal range: 300 ~ 380',
      'rules_out_of_range_error': 'Out of range is considered abnormal',
      'rules_short_circuit_section': 'Short Circuit Test Rules',
      'rules_vdd_short_title': 'Vdd Short (Power Short)',
      'rules_vdd_short_desc': 'Idle value abnormally high, falls into Running range',
      'rules_vdd_short_cond1': 'Condition: Idle value falls into Running threshold range',
      'rules_vdd_short_cond2': 'And Idle value is not within Idle threshold range',
      'rules_vdd_short_reason': 'Cause: Vdd short causes continuous current flow',
      'rules_d12v_short_title': 'Drain-12V Short',
      'rules_d12v_short_desc': 'MOSFET Drain shorted to 12V power on PCB',
      'rules_d12v_short_cond1': 'Condition: Arduino Idle > 1000',
      'rules_d12v_short_cond2': 'And Arduino Running > 1000',
      'rules_d12v_short_feature': 'Feature: Arduino ADC near saturation (10-bit ADC max 1023)',
      'rules_d12v_short_reason': 'Cause: Drain is forced high by 12V',
      'rules_adjacent_short_title': 'Adjacent Pin Short',
      'rules_adjacent_short_desc': 'Short circuit between adjacent GPIO pins',
      'rules_adjacent_short_cond': 'Condition: Adjacent pin Idle baseline change exceeds threshold',
      'rules_adjacent_short_threshold': 'Default threshold: 15',
      'rules_adjacent_short_method': 'Test method: Activate test pin, read adjacent pin value changes',
      'rules_adjacent_short_label': 'Short threshold',
      'rules_diagnostic_section': 'Diagnostic Detection Rules',
      'rules_condition_header': 'Conditions:',
      'rules_load_disconnected_title': 'Load Disconnected',
      'rules_load_disconnected_desc': 'GPIO load (LED, relay, etc.) not properly connected',
      'rules_load_disconnected_cond_header': 'Conditions (all must be met):',
      'rules_load_disconnected_cond1': '1. Arduino Idle and Running difference < 180',
      'rules_load_disconnected_cond2': '2. STM32 Running in 40 ~ 70 (abnormally low)',
      'rules_load_disconnected_cond3': '3. STM32 Idle within normal range',
      'rules_load_disconnected_feature': 'Feature: No current change detected',
      'rules_gd_short_title': 'G-D Short (Gate-Drain Short)',
      'rules_gd_short_desc': 'MOSFET Gate shorted to Drain',
      'rules_gd_short_cond1': '1. Arduino Idle < 10 (near 0)',
      'rules_gd_short_cond2': '2. Arduino Running in 350 ~ 480',
      'rules_gd_short_cond3': '3. STM32 Running in 420 ~ 570',
      'rules_ds_short_title': 'D-S Short (Drain-Source Short)',
      'rules_ds_short_desc': 'MOSFET Drain shorted to Source',
      'rules_ds_short_cond1': '1. Arduino Idle in 25 ~ 60 (falls into Running range)',
      'rules_ds_short_cond2': '2. STM32 Idle in 330 ~ 375 (falls into Running range)',
      'rules_d_grounded_title': 'Drain Grounded',
      'rules_d_grounded_desc': 'MOSFET Drain connected to ground',
      'rules_d_grounded_cond': 'Condition: Arduino Idle < 10 (near 0)',
      'rules_d_grounded_feature': 'Feature: Drain pulled to ground potential',
      'rules_d_grounded_label': 'Arduino ADC <',
      'rules_g_grounded_title': 'Gate Grounded',
      'rules_g_grounded_desc': 'MOSFET Gate connected to ground',
      'rules_g_grounded_cond1': '1. Arduino Idle ≥ 700 (normal)',
      'rules_g_grounded_cond2': '2. Arduino Running ≥ 700 (maintains Idle value)',
      'rules_g_grounded_cond3': '3. STM32 Idle < 50 (very low)',
      'rules_g_grounded_cond4': '4. STM32 Running < 100 (very low)',
      'rules_g_grounded_feature': 'Feature: Gate cannot control, MOSFET not conducting',
      'rules_gs_short_title': 'G-S Short (Gate-Source Short)',
      'rules_gs_short_desc': 'MOSFET Gate shorted to Source',
      'rules_gs_short_cond1': '1. STM32 Running > 400',
      'rules_gs_short_cond2': '2. STM32 Idle < 50',
      'rules_wire_error_title': 'Wire Error Detection',
      'rules_wire_error_desc': 'Arduino side wire misconnected or broken, causing low Idle/Running diff',
      'rules_sensor_section': 'Sensor Detection Rules',
      'rules_sensor_flow_title': 'Flow (Flow Meter)',
      'rules_sensor_flow_desc': 'ID18 - Flow sensor',
      'rules_sensor_flow_arduino': 'Arduino normal range: 0 ~ 10000',
      'rules_sensor_flow_stm32': 'STM32 normal range: 0 ~ 10000',
      'rules_sensor_pressure_co2_title': 'PressureCO2 (CO2 Pressure)',
      'rules_sensor_pressure_co2_desc': 'ID19 - CO2 pressure sensor',
      'rules_sensor_pressure_co2_arduino': 'Arduino normal range: 190 ~ 260',
      'rules_sensor_pressure_co2_stm32': 'STM32 normal range: 930 ~ 980',
      'rules_sensor_pressure_water_title': 'PressureWater (Water Pressure)',
      'rules_sensor_pressure_water_desc': 'ID20 - Water pressure sensor',
      'rules_sensor_pressure_water_arduino': 'Arduino normal range: 190 ~ 260',
      'rules_sensor_pressure_water_stm32': 'STM32 normal range: 930 ~ 980',
      'rules_sensor_mcu_temp_title': 'MCUtemp (MCU Temperature)',
      'rules_sensor_mcu_temp_desc': 'ID21 - MCU internal temperature sensor',
      'rules_sensor_mcu_temp_arduino': 'Arduino normal range: -20°C ~ 100°C (raw value / 10)',
      'rules_sensor_mcu_temp_stm32': 'STM32 normal range: -20°C ~ 100°C',
      'rules_sensor_water_temp_title': 'WATERtemp (Water Temperature)',
      'rules_sensor_water_temp_desc': 'ID22 - Water temperature sensor (DS18B20)',
      'rules_sensor_water_temp_stm32': 'STM32 normal range: -20°C ~ 100°C',
      'rules_sensor_temp_error_title': 'Temperature Sensor Error Value',
      'rules_sensor_temp_error_desc': 'Temperature sensor reporting 85°C indicates not connected or damaged',
      'rules_sensor_temp_error_label': 'Error temp value (°C)',
      'rules_sensor_temp_error_85': 'Error value: 85°C indicates sensor not connected or damaged',
      'rules_sensor_bib_temp_title': 'BIBtemp (BIB Temperature)',
      'rules_sensor_bib_temp_desc': 'ID23 - BIB temperature sensor (DS18B20)',
      'rules_sensor_bib_temp_stm32': 'STM32 normal range: -20°C ~ 100°C',
      'rules_polling_retry_step1': 'First round: Read all IDs sequentially',
      'rules_polling_retry_step2': 'Second round: Only retry IDs with no data',
      'rules_polling_retry_max': 'Maximum 5 retries per ID',
      'rules_polling_retry_wait': 'Wait time: Hardware 300ms, Sensor 400ms',
      'rules_polling_sensor_wait_label': 'Sensor wait (ms)',

      // Detection rules — 僅 BodyDoor
      'rules_33v_section': '3.3V Power Anomaly Detection',
      'rules_33v_title': '3.3V Power Anomaly Rule',
      'rules_33v_desc': 'When all 5 ADC values of the 3.3V sensors are below threshold, it indicates 3.3V power anomaly',
      'rules_33v_ids': 'Monitored IDs: BibTemp, WaterTemp, Leak, WaterPressure, CO2Pressure',
      'rules_33v_threshold_label': 'Anomaly threshold (below this value)',
      'rules_33v_condition': 'Trigger condition: ALL 5 IDs must be below threshold simultaneously',
      'rules_33v_action_realtime': 'Real-time warning: Red warning banner on DataStorage and AutoDetection pages',
      'rules_33v_action_result': 'Detection result: Auto detection marks "3.3V power anomaly"',
      'rules_body12v_section': 'Body 12V Power Anomaly Detection',
      'rules_body12v_title': 'Body 12V Power Anomaly Rule',
      'rules_body12v_desc': 'When all 7 Body 12V channel ADC values are below threshold AND 3.3V anomaly is triggered, it indicates Body 12V power failure',
      'rules_body12v_ids': 'Monitored IDs: AmbientRL, CoolRL, SparklingRL, WaterPump, O3, MainUVC, FlowMeter',
      'rules_body12v_threshold_label': 'Anomaly threshold (below this value)',
      'rules_body12v_condition': 'Trigger condition: ALL 7 IDs must be below threshold simultaneously',
      'rules_body12v_prerequisite': 'Prerequisite: 3.3V power anomaly must also be triggered (hierarchical check)',
      'rules_body12v_action_realtime': 'Real-time warning: Deep orange warning banner on DataStorage and AutoDetection pages',
      'rules_body12v_action_result': 'Detection result: Auto detection marks "Body 12V power anomaly"',
      'rules_door24v_section': 'Door 24V Boost Circuit Anomaly Detection',
      'rules_door24v_title': 'Door 24V Boost Circuit Anomaly Rule',
      'rules_door24v_desc': 'When BP_24V ADC value is below threshold, it indicates boost circuit failure',
      'rules_door24v_ids': 'Monitored ID: BP_24V',
      'rules_door24v_threshold_label': 'Anomaly threshold (below this value)',
      'rules_door24v_condition': 'Trigger condition: BP_24V value below threshold',
      'rules_door24v_action_realtime': 'Real-time warning: Purple warning banner on DataStorage and AutoDetection pages',
      'rules_door24v_action_result': 'Detection result: Auto detection marks "Door 24V boost circuit anomaly"',
      'rules_door12v_section': 'Door 12V Power Anomaly Detection',
      'rules_door12v_title': 'Door 12V Power Anomaly Rule',
      'rules_door12v_desc': 'When all 6 Door 12V channel ADC values are below threshold, it indicates Door 12V power failure',
      'rules_door12v_ids': 'Monitored IDs: SpoutUVC, MixUVC, FlowMeter2, BP_12V, BP_UpScreen, BP_LowScreen',
      'rules_door12v_threshold_label': 'Anomaly threshold (below this value)',
      'rules_door12v_condition': 'Trigger condition: ALL 6 IDs must be below threshold simultaneously',
      'rules_door12v_action_realtime': 'Real-time warning: Indigo warning banner on DataStorage and AutoDetection pages',
      'rules_door12v_action_result': 'Detection result: Auto detection marks "Door 12V power anomaly"',

      // Operation page（僅 Main）
      'operation_auto_connect': 'Auto Connect STM32',
      'operation_connecting': 'Connecting...',
      'operation_connected': 'STM32 Connected',
      'operation_connect_failed': 'STM32 Connection Failed',
      'operation_warm_water': 'Warm Water',
      'operation_stop': 'Stop',
      'operation_warm_water_desc': 'Open ID10~ID14',
      'operation_stop_desc': 'Close ID0~ID17',
      'operation_stm32_not_connected': 'Please connect STM32 first',
      'operation_warm_water_sent': 'Warm water command sent (ID10~ID14 opened)',
      'operation_stop_sent': 'Stop command sent (ID0~ID17 closed)',

      // Threshold settings（共用）
      'threshold_settings': 'Threshold Settings',
      'threshold_settings_desc': 'Configure value ranges for auto detection',
      'arduino_idle_threshold': 'Arduino Idle Threshold',
      'idle_threshold': 'Idle Threshold',
      'min_value': 'Min',
      'max_value': 'Max',
      'threshold_range': 'Range',
      'reset_to_defaults': 'Reset to Defaults',
      'reset_all_confirm': 'Are you sure you want to reset all thresholds to defaults?',
      'reset_success': 'Reset to defaults',
      'save_success': 'Settings saved',
      'apply_to_all': 'Apply to All IDs',
      'edit_threshold': 'Edit Threshold',
      'id_label': 'ID {id}',
      'value_out_of_range': 'Value out of range',

      // Threshold settings — 僅 Main
      'arduino_running_threshold': 'Arduino Running Threshold',
      'stm32_idle_threshold': 'STM32 Idle Threshold',
      'stm32_running_threshold': 'STM32 Running Threshold',
      'running_threshold': 'Running Threshold',
      'sensor_threshold': 'Sensor Threshold',
      'diff_threshold': 'Difference Threshold',

      // Threshold settings — 衝突 key（以前綴區分）
      'main_hardware_threshold': 'Hardware Threshold (ID 0-17)',
      'bodydoor_hardware_threshold': 'Hardware Threshold (ID 0-18)',

      // Firmware upload（僅 Main）
      'firmware_upload': 'Firmware Upload',
      'checking_stlink': 'Checking ST-Link connection...',
      'stlink_connected': 'ST-Link Connected',
      'stlink_not_connected': 'ST-Link Not Connected',
      'refresh_stlink': 'Refresh ST-Link Status',
      'cli_not_found': 'STM32CubeProgrammer CLI Not Found',
      'cli_not_found_hint': 'Please ensure STM32CubeProgrammer is installed. CLI tool should be at:',
      'status': 'Status',
      'version': 'Version',
      'serial_number': 'Serial Number',
      'firmware_file': 'Firmware File',
      'click_to_select': 'Click to select firmware file',
      'select_firmware_file': 'Select Firmware File',
      'supported_formats': 'Supported formats: .elf, .bin, .hex',
      'program_options': 'Program Options',
      'verify_after_program': 'Verify After Program',
      'verify_hint': 'Verify that written data is correct',
      'reset_after_program': 'Reset After Program',
      'reset_hint': 'Automatically reset MCU after programming',
      'program_firmware': 'Program Firmware',
      'programming': 'Programming...',
      'please_select_firmware': 'Please select a firmware file first',
      'starting_program': 'Starting programming...',
      'waiting_stm32_startup': 'Waiting for STM32 startup...',
      'program_success': 'Firmware programmed successfully',
      'erase': 'Erase',
      'reset': 'Reset',
      'confirm_erase': 'Confirm Erase',
      'erase_warning': 'This will erase all firmware on STM32. Are you sure?',
      'erasing_flash': 'Erasing Flash...',
      'resetting_mcu': 'Resetting MCU...',
      'progress': 'Progress',
      'stlink_frequency': 'ST-Link Frequency',
      'stlink_frequency_hint': 'SWD communication frequency (kHz)',
      'cli_output': 'CLI Output',
      'select_other_file': 'Select other file...',
      'firmware_folder_hint': 'Place firmware files in the firmware folder',
      'connect_mode': 'Connect Mode',
      'connect_mode_hint': 'ST-Link connection mode',
      'reset_mode': 'Reset Mode',
      'reset_mode_hint': 'MCU reset method',
      'program_timeout': 'Program Timeout',
      'erase_timeout': 'Erase Timeout',
      'reset_timeout': 'Reset Timeout',
      'check_timeout': 'Connection Check Timeout',
      'disconnecting_stm32_for_program': 'Disconnecting STM32 before programming...',
      'program_success_retry': 'Firmware programmed successfully (attempt {attempt}, {frequency} kHz)',
      'program_timeout_error': 'Program timeout (120s)',
      'firmware_file_not_found': 'Firmware file not found',
      'unsupported_file_format': 'Unsupported file format: .{extension}',
      'stlink_not_detected': 'ST-Link not connected',
      'target_not_connected': 'Target MCU not connected',
      'flash_erase_failed': 'Flash erase failed',
      'program_failed': 'Program failed',
      'execution_error': 'Execution error',
      'erase_timeout_error': 'Erase timeout (60s)',
      'erase_completed': 'Erase completed',
      'erase_failed': 'Erase failed',
      'erase_error': 'Erase error',
      'mcu_reset_timeout_error': 'Reset timeout (30s)',
      'mcu_reset_completed': 'MCU reset completed',
      'mcu_reset_failed': 'MCU reset failed',
      'mcu_reset_error': 'MCU reset error',
      'no_firmware_files': 'No firmware files',
      'select_firmware': 'Select firmware',
      'program_and_detect': 'Program & Detect',

      // CLI tool check dialog（僅 Main）
      'cli_check_title': 'Missing Required Tools',
      'cli_check_description': 'The following external tools are required for programming. Please install:',
      'cli_status_installed': 'Installed',
      'cli_status_not_found': 'Not detected',
      'cli_install_instruction': 'Installation:',
      'cli_installer_found': 'Installer found',
      'cli_run_installer': 'Run Installer',
      'cli_download_instruction': 'Download from ST website:',
      'cli_installer_tip': 'Tip: You can place the installer in tools folder for future use',
      'cli_open_tools_folder': 'Open tools folder',
      'cli_skip_continue': 'Skip, continue anyway',
      'cli_recheck': 'Recheck',

      // Cross-mode detection（衝突 — 以前綴區分）
      'wrong_mode_detected': 'Different Device Detected',
      'wrong_mode_detected_title': 'Different Device Detected',
      'main_wrong_mode_detected_message': 'Detected Body&Door Board Arduino. Switch to the correct mode?',
      'bodydoor_wrong_mode_detected_message': 'Detected Main Board Arduino. Switch to the correct mode?',
      'switch_to_bodydoor_mode': 'Switch to Body&Door Mode',
      'switch_to_main_mode': 'Switch to Main Mode',
      'switch_mode': 'Switch Mode',
    },
  };
}

/// 全域快捷方法，方便使用
String tr(String key) => LocalizationService().tr(key);

/// 全域帶參數翻譯方法
String trParams(String key, Map<String, dynamic> params) =>
    LocalizationService().trParams(key, params);
